// This file was autogenerated by C:\Users\surfing\Documents\HackDay\closure\depswriter.py.
// Please do not edit.
goog.addDependency('EvaluationMatrix/js/EvaluationMatrix.js', ['hackday.EvaluationMatrix'], ['hackday.KeyEditTableHelper']);
goog.addDependency('EvaluationMatrix/js/EvaluationMatrixConfiguration.js', ['hackday.EvaluationMatrix.ConfigurationComponent'], []);
goog.addDependency('EvaluationMatrix/js/EvaluationMatrixSetup.js', ['hackday.EvaluationMatrixSetup'], ['KeyTableModule', 'hackday.EvaluationMatrix', 'hackday.EvaluationMatrix.ConfigurationComponent', 'jquery.collapsible']);
goog.addDependency('EvaluationMatrix/js/KeyEditTableHelper.js', ['hackday.KeyEditTableHelper'], []);
goog.addDependency('common/js/ColVis.js', ['ColVis'], []);
goog.addDependency('common/js/KeyTable.js', ['KeyTable'], []);
goog.addDependency('common/js/KeyTableModule.js', ['KeyTableModule'], ['ColVis', 'KeyTable', 'TableTools', 'jquery.dataTables', 'jquery.jeditable']);
goog.addDependency('common/js/TableTools.js', ['TableTools'], []);
goog.addDependency('common/js/jquery.collapsible.js', ['jquery.collapsible'], []);
goog.addDependency('common/js/jquery.dataTables.js', ['jquery.dataTables'], []);
goog.addDependency('common/js/jquery.jeditable.js', ['jquery.jeditable'], []);
