// This file was autogenerated by C:\Users\surfing\Desktop\yguan-Hack_Day_JS_Projects\closure\depswriter.py.
// Please do not edit.
goog.addDependency('InteractiveCanvas/js/data/shapes.js', ['hackday.interactiveCanvas.data.shapes'], []);
goog.addDependency('InteractiveCanvas/js/data/us-states.js', ['hackday.interactiveCanvas.data.states'], []);
goog.addDependency('InteractiveCanvas/js/data/world.js', ['hackday.interactiveCanvas.data.world'], []);
goog.addDependency('InteractiveCanvas/js/map.js', ['hackday.interactiveCanvas.map'], ['paper']);
goog.addDependency('InteractiveCanvas/js/shapeMaker.js', ['hackday.interactiveCanvas.shapeMaker'], ['paper']);
goog.addDependency('common/js/ColVis.js', ['ColVis'], []);
goog.addDependency('common/js/KeyTable.js', ['KeyTable'], []);
goog.addDependency('common/js/KeyTableModule.js', ['KeyTableModule'], ['ColVis', 'KeyTable', 'TableTools', 'jquery.dataTables', 'jquery.jeditable']);
goog.addDependency('common/js/TableTools.js', ['TableTools'], []);
goog.addDependency('common/js/jquery.collapsible.js', ['jquery.collapsible'], []);
goog.addDependency('common/js/jquery.dataTables.js', ['jquery.dataTables'], []);
goog.addDependency('common/js/jquery.jeditable.js', ['jquery.jeditable'], []);
goog.addDependency('common/js/paper.js', ['paper'], []);
